from src.locators.web_inputs_locators import WebInputsPageLocators
from src.locators.add_remove_locators import AddRemovePageLocators
from src.locators.notification_locators import NotificationLocators
