from src.locators.web_inputs_locators import WebInputsPageLocators
from src.locators.add_remove_locators import AddRemovePageLocators
from src.locators.notification_locators import NotificationLocators
from src.locators.dynamic_table_locators import DynamicTableLocators
from src.locators.browser_info_locators import BrowserInfoPageLocators
